### ISSUE TITLE
How to update Brave without rebuilding the container?

### ISSUE THREAD

**Issue by hugobuddel** [truatpasteurdotfr/singularity-docker-fedora30-brave#1]
Currently using your container to run Brave, as per https://github.com/brave/brave-browser/issues/4280#issuecomment-519914586 . Much thanks for setting this up!

So I'm now running version 0.66.100, better than what I had, but still 2 weeks old. Being new to singularity, it is not clear to me how to upgrade this. Below are three options that I'm considering, in order of decreasing preference, but increasing level of confidence of success. Could you provide some advice @truatpasteurdotfr?

- Upgrade Brave in the running instance. Is this possible? Nothing even shows when doing `singularity instance list`. Are the instances even persistent so Brave would stay upgraded when restarting the instance?
- Add upgrading of Brave to the `runscript` of the Singularity file. Does this make sense? I suppose this would upgrade Brave each time a container image is ran. But that's fine, because Brave is upgrading more often than I restart my browser, so it needs to upgrade every time anyway. Maybe I can give this a try.
- Rebuilding the entire Singularity container regularly. I don't have root access on the Centos machine where I need the container, so this is a bit cumbersome.

**Comment by truatpasteurdotfr** [comment]
the container file is read-only by definition... you have to rebuild it every time you need to upgrade any component, and you need a root access to use a recipe for building (unless your linux distribution is recent enough to use usernamespace).
You don't have to run centos to build the container, the recipe can be used on any ilnux distribution running a singularity 3 version.
I will rebuild the f30-brave asap and replace the old one.

**Comment by truatpasteurdotfr** [comment]
tagged: 2019-08-25-1829 version uploaded.

**Comment by hugobuddel** [comment]
I've created a branch to clarify what I meant with my second suggestion: upgrade Brave every time it launches.

I'll try it myself soon. My Centos machine at work does have user namespaces, so maybe I can even create a container image on the machine itself somehow.

**Comment by truatpasteurdotfr** [comment]
You might be able to do so with writable overlays and yum; maybe with rpm2cpio as a user in a 'sandbox'.

**Comment by truatpasteurdotfr** [comment]
let's open the discussion to the singularity slack channel  :P

**Comment by hugobuddel** [comment]
I'll do some experiments first to learn more about Singularity. I've requested to join the Slack though.
