### ISSUE TITLE
Propagate time zone

### ISSUE THREAD

**Issue by hugobuddel** [truatpasteurdotfr/singularity-docker-fedora30-brave#3]
Brave uses the UTC time zone when started from the container (Centos 7 host).

E.g. https://browserleaks.com/javascript shows timeZone UTC.

`date` returns the correct information though:

    $ singularity exec library://tru/default/f30-brave date
    Wed Jan  8 13:44:49 CET 2020

but `timedatectl` does not:

    $ singularity exec library://tru/default/f30-brave timedatectl
    System has not been booted with systemd as init system (PID 1). Can't operate.
    Failed to create bus connection: Host is down

My guess is that Brave uses a method to get the timezone that fails, so it defaults to UTC.

**Comment by truatpasteurdotfr** [comment]
you need to bind /run to systemd (on my cntos7 host):
```
[tru@elitebook840g3 ~]$ singularity exec library://tru/default/f30-brave date
INFO:    Downloading library image
Sat Jan 11 21:56:54 CET 2020
[tru@elitebook840g3 ~]$ date
Sat Jan 11 21:57:10 CET 2020
[tru@elitebook840g3 ~]$ timedatectl
      Local time: Sat 2020-01-11 21:57:18 CET
  Universal time: Sat 2020-01-11 20:57:18 UTC
        RTC time: Sat 2020-01-11 20:57:18
       Time zone: Europe/Paris (CET, +0100)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: no
 Last DST change: DST ended at
                  Sun 2019-10-27 02:59:59 CEST
                  Sun 2019-10-27 02:00:00 CET
 Next DST change: DST begins (the clock jumps one hour forward) at
                  Sun 2020-03-29 01:59:59 CET
                  Sun 2020-03-29 03:00:00 CEST
[tru@elitebook840g3 ~]$ singularity exec library://tru/default/f30-brave timedatectl
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
[tru@elitebook840g3 ~]$ singularity exec -B /run library://tru/default/f30-brave timedatectl
               Local time: Sat 2020-01-11 21:58:33 CET
           Universal time: Sat 2020-01-11 20:58:33 UTC
                 RTC time: Sat 2020-01-11 20:58:33
                Time zone: Europe/Paris (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

```

**Comment by hugobuddel** [comment]
Thank you @truatpasteurdotfr, this is my only singularity container so far, so still learning.

I actually do use `-B /run` when running the container normally to run brave and should have ran these examples in the same way, my apologies.

But the new tab and the website above show that Brave is using UTC as timezone. Unclear where it gets that from. Maybe from `/etc/localtime`:

````
$ singularity exec -B /run library://tru/default/f30-brave ls -l /etc/localtime
lrwxrwxrwx. 1 root root 29 Sep 26 09:50 /etc/localtime -> ../usr/share/zoneinfo/Etc/UTC
````

Trying to rebind those files has so far not been successful. E.g.

````
$ ls -l /etc/localtime 
lrwxrwxrwx. 1 root root 38 Aug 22  2017 /etc/localtime -> ../usr/share/zoneinfo/Europe/Amsterdam
$ singularity run -B /etc/localtime -B /run library://tru/default/f30-brave
````

stil makes Brave think it should use UTC.

**Comment by truatpasteurdotfr** [comment]
right, the docker image is defined with UTC as you have noticed. 
You may be able to workaround that by binding the container linked /etc/localtime with your host:
```
[tru@elitebook840g3 ~]$ singularity exec -B /run  library://tru/default/f30-brave md5sum /etc/localtime
07c4012a5a941cd20bd4baab9b10e3f4  /etc/localtime
[tru@elitebook840g3 ~]$ singularity exec -B /run -B  /usr/share/zoneinfo/Europe/Amsterdam:/usr/share/zoneinfo/Etc/UTC library://tru/default/f30-brave md5sum /etc/localtime
e3b0d618da0bd60d894183dd0d53923e  /etc/localtime
```
You need to bind the actual files linked, not just the soft link.

**Comment by hugobuddel** [comment]
It seems I'm doing something very weird. At least I don't understand what's going on at all: on my container, `/etc/localtime` is `/usr/share/zoneinfo/Europe/Amsterdam` from the host.

(My apologies, the host is Scientific Linux 7.7, not Centos 7 as mentioned earlier.)

The host:
```
$ ls -l /etc/localtime /usr/share/zoneinfo/Europe/Amsterdam /usr/share/zoneinfo/Etc/UTC
lrwxrwxrwx. 1 root root   38 Aug 22  2017 /etc/localtime -> ../usr/share/zoneinfo/Europe/Amsterdam
-rw-r--r--  8 root root  118 Sep 23 17:02 /usr/share/zoneinfo/Etc/UTC
-rw-r--r--  1 root root 2923 Sep 23 17:02 /usr/share/zoneinfo/Europe/Amsterdam

$ md5sum /etc/localtime /usr/share/zoneinfo/Europe/Amsterdam /usr/share/zoneinfo/Etc/UTC
e3b0d618da0bd60d894183dd0d53923e  /etc/localtime
e3b0d618da0bd60d894183dd0d53923e  /usr/share/zoneinfo/Europe/Amsterdam
c79354b8dbee09e62bbc3fb544853283  /usr/share/zoneinfo/Etc/UTC
```

The container:
```
$ singularity exec -B /run library://tru/default/f30-brave ls -l /etc/localtime /usr/share/zoneinfo/Europe/Amsterdam /usr/share/zoneinfo/Etc/UTC
lrwxrwxrwx. 1 root root   29 Sep 26 09:50 /etc/localtime -> ../usr/share/zoneinfo/Etc/UTC
-rw-r--r--  1 root root 2923 Sep 23 17:02 /usr/share/zoneinfo/Etc/UTC
-rw-r--r--. 1 root root 2940 Sep 27 04:12 /usr/share/zoneinfo/Europe/Amsterdam

$ singularity exec -B /run library://tru/default/f30-brave md5sum /etc/localtime /usr/share/zoneinfo/Europe/Amsterdam /usr/share/zoneinfo/Etc/UTC
e3b0d618da0bd60d894183dd0d53923e  /etc/localtime
436f08577a0cca7e08906ff30654ff37  /usr/share/zoneinfo/Europe/Amsterdam
e3b0d618da0bd60d894183dd0d53923e  /usr/share/zoneinfo/Etc/UTC
```

The md5sum and even the timestamps match. So I seem to have somehow copied the host `/etc/localtime` over the `/etc/localtime` of the container? I've removed my entire `~/.singularity` directory and rebooted the host but the discrepancy remains.

I don't understand what is going on at all. I don't have root access to the host (work machine); so I'm assuming everything is correct there. Maybe Brave is just looking at the filename that `/etc/localtime` is pointing to but not the contents of that file?

**Comment by truatpasteurdotfr** [comment]
- singularity is managing /etc/localtime inside the container from your host (check /etc/singularity/singularity.conf and the `bind path = ` lines).
- but it is failing for the symbolic link, that **why you need to add a second binding information for /usr/share/zoneinfo/Etc/UTC**

```
singularity exec -B /run \
library://tru/default/f30-brave md5sum /etc/localtime /usr/share/zoneinfo/Europe/Amsterdam /usr/share/zoneinfo/Etc/UTC
```
and
```
singularity exec -B /run \
-B  /usr/share/zoneinfo/Europe/Amsterdam:/usr/share/zoneinfo/Etc/UTC  \
library://tru/default/f30-brave md5sum /etc/localtime /usr/share/zoneinfo/Europe/Amsterdam /usr/share/zoneinfo/Etc/UTC
```

**Comment by hugobuddel** [comment]
Ah thank you. The `/etc/localtime` bind is automatic!

However, both your commands give the exact same output (singularity version 3.5.2-1.1.el7):
````
singularity exec -B /run \
library://tru/default/f30-brave md5sum /etc/localtime /usr/share/zoneinfo/Europe/Amsterdam /usr/share/zoneinfo/Etc/UTC

e3b0d618da0bd60d894183dd0d53923e  /etc/localtime
436f08577a0cca7e08906ff30654ff37  /usr/share/zoneinfo/Europe/Amsterdam
e3b0d618da0bd60d894183dd0d53923e  /usr/share/zoneinfo/Etc/UTC

singularity exec -B /run \
-B  /usr/share/zoneinfo/Europe/Amsterdam:/usr/share/zoneinfo/Etc/UTC  \
library://tru/default/f30-brave md5sum /etc/localtime /usr/share/zoneinfo/Europe/Amsterdam /usr/share/zoneinfo/Etc/UTC

e3b0d618da0bd60d894183dd0d53923e  /etc/localtime
436f08577a0cca7e08906ff30654ff37  /usr/share/zoneinfo/Europe/Amsterdam
e3b0d618da0bd60d894183dd0d53923e  /usr/share/zoneinfo/Etc/UTC
````

I've just installed singularity on one of my home machines (Ubuntu 16.04 LTS, singularity 3.5.2) and the behavior is the same (except the hash of /etc/localtime is dc1e10469cc1a7188ec7b3043a6cff5b). Have not yet tried to run Brave through the container though. (Edit: running Brave through the singularity container on the Ubuntu machine also uses timezone UTC.)

So it seems that the default bind of `/etc/localtime` does not actually change what `/etc/localtime` links to, but it changes the content of the file it links to. So:

* `/etc/localtime` still points to `/usr/share/zoneinfo/Etc/UTC` in the instance, and
* the contents of `/usr/share/zoneinfo/Etc/UTC` is replaced by the contents of `/etc/localtime` of the host.

My guess is that Brave ignores the contents of `/etc/localtime` and just looks at the name. (Or maybe `/etc/localtime` is a red herring and it fetches the timezone from somewhere else entirely.) So I'll try to make the symlink point to another file, although I'm not yet sure how to do so.

**Comment by hugobuddel** [comment]
Hmm maybe this is a problem with specific singularity versions. I've noticed the problem since this month and our singularity executable was updated December 17th, perhaps after I last used it.

Symlink issues with `/etc/localtime` are described in https://github.com/sylabs/singularity/issues/4797 and https://github.com/sylabs/singularity/pull/4800 from November, maybe related. I'll do some investigation.

**Comment by hugobuddel** [comment]
Same behavior in 3.5.0 and 3.2.1, so maybe not version related... (I couldn't get 3.0.1 and 2.6.1 to compile easily so gave up after that.)

Did you manage to get Brave to use the proper timezone @truatpasteurdotfr?

**Comment by hugobuddel** [comment]
Success! By creating a persistent overlay [1] I was able to create an overlay where `/etc/localtime` points to `../usr/share/zoneinfo/Europe/Amsterdam` and now brave has the correct time.

It doesn't even seem to matter what is in `/usr/share/zoneinfo/Europe/Amsterdam`. I copied over the contents from `Cuba` into that file and Brave still started with the right timezone. (Unfortunately that file was bound from the host, so now my host thought I was on Cuban time... Backups++.) (I could not use the `mkfs.ext3 -d` command because my e2fsprogs is probably too old.)

Note that browserleaks [2] gave the timezone as "Europe/Amsterdam", strengthening that it gets the timezone information directly from the filename.

[1] https://sylabs.io/guides/3.5/user-guide/persistent_overlays.html
[2] https://browserleaks.com/javascript

**Comment by hugobuddel** [comment]
Having `/etc/localtime` point to a file that does not exist or to a file with a name that does not correspond to a timezone will result in UTC time in Brave and "Etc/Unknown" reported by browserleaks.

Brave (or Chromium?) apparently indeed takes the name of the file that `/etc/localtime` points to, but does not trust the actual contents of that file and uses its own database instead.

So we need to change what `/etc/localtime` points to, not the contents of that file. There must be an easier way than creating an overlay though..

**Comment by truatpasteurdotfr** [comment]
thanks for taking time to investigate the issue!

Maybe brave is using something like `realpath /etc/localtime` which yield /usr/share/zoneinfo/Europe/Amsterdam and derive the timezone from that information...

So you need to replace the path to the file to a user controlled path/filename to fool brave's timezone detection.

**Comment by hugobuddel** [comment]
Yeah, that's essentially what I did with the overlay. I'll write it up sometime next week and give you a PR to add it to the readme.

I'll also investigate whether there is a better way to do this. It seems weird that if you bind a symlink with another symlink, that it leaves the symlinks intact but instead bind their targets.

It is a minor issue, so this workaround is good enough for now. My main issue is with Remember The Milk (TODO-list website) that puts all due dates on the wrong day if your timezone is wrong (which I think is a bug).

**Comment by hugobuddel** [comment]
I've asked @bedroge, our local singularity expert, and he solved it as follows:
````
env TZ="Europe/Amsterdam" singularity run -B /run library://tru/default/f30-brave 
````
